name: Continuous Integration Workflow
on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ develop ]
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Run Lint
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
  linter:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: npm run lint
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: npm run test:cov
